/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVolunteersRouteImport } from './routes/_app.volunteers'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppParticipantsRouteImport } from './routes/_app.participants'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppFamiliesRouteImport } from './routes/_app.families'
import { Route as AppDonorsRouteImport } from './routes/_app.donors'
import { Route as AppDonationsRouteImport } from './routes/_app.donations'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppVolunteerIdRouteImport } from './routes/_app.volunteer.$id'
import { Route as AppSuppliersIdRouteImport } from './routes/_app.suppliers_.$id'
import { Route as AppProjectIdRouteImport } from './routes/_app.project.$id'
import { Route as AppFamiliesIdRouteImport } from './routes/_app.families_.$id'
import { Route as AppDonorIdRouteImport } from './routes/_app.donor.$id'
import { Route as AppDonationIdRouteImport } from './routes/_app.donation.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVolunteersRoute = AppVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsRoute = AppParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFamiliesRoute = AppFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsRoute = AppDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AppRoute,
} as any)
const AppDonationsRoute = AppDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppVolunteerIdRoute = AppVolunteerIdRouteImport.update({
  id: '/volunteer/$id',
  path: '/volunteer/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers_/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFamiliesIdRoute = AppFamiliesIdRouteImport.update({
  id: '/families_/$id',
  path: '/families/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorIdRoute = AppDonorIdRouteImport.update({
  id: '/donor/$id',
  path: '/donor/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDonationIdRoute = AppDonationIdRouteImport.update({
  id: '/donation/$id',
  path: '/donation/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/donations': typeof AppDonationsRoute
  '/donors': typeof AppDonorsRoute
  '/families': typeof AppFamiliesRoute
  '/finance': typeof AppFinanceRoute
  '/participants': typeof AppParticipantsRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/volunteers': typeof AppVolunteersRoute
  '/donation/$id': typeof AppDonationIdRoute
  '/donor/$id': typeof AppDonorIdRoute
  '/families/$id': typeof AppFamiliesIdRoute
  '/project/$id': typeof AppProjectIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/volunteer/$id': typeof AppVolunteerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/donations': typeof AppDonationsRoute
  '/donors': typeof AppDonorsRoute
  '/families': typeof AppFamiliesRoute
  '/finance': typeof AppFinanceRoute
  '/participants': typeof AppParticipantsRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/volunteers': typeof AppVolunteersRoute
  '/donation/$id': typeof AppDonationIdRoute
  '/donor/$id': typeof AppDonorIdRoute
  '/families/$id': typeof AppFamiliesIdRoute
  '/project/$id': typeof AppProjectIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/volunteer/$id': typeof AppVolunteerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/donations': typeof AppDonationsRoute
  '/_app/donors': typeof AppDonorsRoute
  '/_app/families': typeof AppFamiliesRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/participants': typeof AppParticipantsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/volunteers': typeof AppVolunteersRoute
  '/_app/donation/$id': typeof AppDonationIdRoute
  '/_app/donor/$id': typeof AppDonorIdRoute
  '/_app/families_/$id': typeof AppFamiliesIdRoute
  '/_app/project/$id': typeof AppProjectIdRoute
  '/_app/suppliers_/$id': typeof AppSuppliersIdRoute
  '/_app/volunteer/$id': typeof AppVolunteerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/donations'
    | '/donors'
    | '/families'
    | '/finance'
    | '/participants'
    | '/projects'
    | '/reports'
    | '/suppliers'
    | '/users'
    | '/volunteers'
    | '/donation/$id'
    | '/donor/$id'
    | '/families/$id'
    | '/project/$id'
    | '/suppliers/$id'
    | '/volunteer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/dashboard'
    | '/donations'
    | '/donors'
    | '/families'
    | '/finance'
    | '/participants'
    | '/projects'
    | '/reports'
    | '/suppliers'
    | '/users'
    | '/volunteers'
    | '/donation/$id'
    | '/donor/$id'
    | '/families/$id'
    | '/project/$id'
    | '/suppliers/$id'
    | '/volunteer/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/donations'
    | '/_app/donors'
    | '/_app/families'
    | '/_app/finance'
    | '/_app/participants'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/suppliers'
    | '/_app/users'
    | '/_app/volunteers'
    | '/_app/donation/$id'
    | '/_app/donor/$id'
    | '/_app/families_/$id'
    | '/_app/project/$id'
    | '/_app/suppliers_/$id'
    | '/_app/volunteer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/volunteers': {
      id: '/_app/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof AppVolunteersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/participants': {
      id: '/_app/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AppParticipantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/families': {
      id: '/_app/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof AppFamiliesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donors': {
      id: '/_app/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof AppDonorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donations': {
      id: '/_app/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AppDonationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/volunteer/$id': {
      id: '/_app/volunteer/$id'
      path: '/volunteer/$id'
      fullPath: '/volunteer/$id'
      preLoaderRoute: typeof AppVolunteerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers_/$id': {
      id: '/_app/suppliers_/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$id': {
      id: '/_app/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/families_/$id': {
      id: '/_app/families_/$id'
      path: '/families/$id'
      fullPath: '/families/$id'
      preLoaderRoute: typeof AppFamiliesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donor/$id': {
      id: '/_app/donor/$id'
      path: '/donor/$id'
      fullPath: '/donor/$id'
      preLoaderRoute: typeof AppDonorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donation/$id': {
      id: '/_app/donation/$id'
      path: '/donation/$id'
      fullPath: '/donation/$id'
      preLoaderRoute: typeof AppDonationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonationsRoute: typeof AppDonationsRoute
  AppDonorsRoute: typeof AppDonorsRoute
  AppFamiliesRoute: typeof AppFamiliesRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppParticipantsRoute: typeof AppParticipantsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVolunteersRoute: typeof AppVolunteersRoute
  AppDonationIdRoute: typeof AppDonationIdRoute
  AppDonorIdRoute: typeof AppDonorIdRoute
  AppFamiliesIdRoute: typeof AppFamiliesIdRoute
  AppProjectIdRoute: typeof AppProjectIdRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppVolunteerIdRoute: typeof AppVolunteerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDonationsRoute: AppDonationsRoute,
  AppDonorsRoute: AppDonorsRoute,
  AppFamiliesRoute: AppFamiliesRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppParticipantsRoute: AppParticipantsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppVolunteersRoute: AppVolunteersRoute,
  AppDonationIdRoute: AppDonationIdRoute,
  AppDonorIdRoute: AppDonorIdRoute,
  AppFamiliesIdRoute: AppFamiliesIdRoute,
  AppProjectIdRoute: AppProjectIdRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppVolunteerIdRoute: AppVolunteerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
